# Project information
site_name: 'IA Portfolio'
site_description: 'Estudos de inteligência artificial.'
site_author: 'Filipe Machado'

# Repository
repo_name: 'fmaachadoo/artificial-intelligence-study-portfolio'
repo_url: 'https://github.com/fmaachadoo/artificial-intelligence-study-portfolio'

# Configuration
nav:
  - Início: 'index.md'
  - Introdução: 'intro.md'
  - História: 'history.md'
  - Estado da Arte: 'state-of-the-art.md'
  - Agentes: 'agent.md'
  - Agentes de Soluções de Problemas: 'problem_solving_agents.md'
  - Algoritmos de Busca: 'search_algorithms.md'
  - Funções Heurísticas: 'heuristics.md'
  - Busca em ambientes complexos: 'complex_environments.md'
  - Algoritmos genéticos: 'genetic_algorithms.md'
  - Discussões (Porfolio 2): 'portfolio_2_discussions.md'
  - Projetos e problemas (Porfolio 2): 'portfolio_2_projects.md'
  - CSPs (Portfolio 3): 'csp.md'

# Theme
theme:
  name: 'material'
  language: 'pt-br'
  palette:
    scheme: slate

# Extra theme customization
extra:
  theme:
    features:
      - 'navigation.tabs'
      - 'navigation.tabs.sticky'
      - 'dark_mode'

# Plugins (Optional)
plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format